services:
  codexaction:
    image: codexaction
    build:
      context: .github/actions/codex
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
